version: "3"

services:
  webbitiimibot:
    build:
      context: ..
      dockerfile: .devcontainer/dev.Dockerfile
    ports:
      - 80:80
    volumes:
      - ~/.ssh:/.ssh
      - ..:/webbitiimibot:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=webbitiimibot
      - POSTGRES_USER=webbitiimibot

    
